
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Minitest01
    username: root
    password:
    hikari:
      pool-name: minitest01_pool
      maximum-pool-size: 10
      minimum-idle: 3
    application.name: minitest01-jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  logging:
    level:
      com.zaxxer.hikari: debug
      org.springframework.transaction: debug

